name:                htin
version:             0.1.0.0
github:              "aktowns/htin"
license:             BSD3
author:              "Ashley Towns"
maintainer:          "tin@ashleytowns.id.au"
copyright:           "2018 Ashley Towns"

extra-source-files:
- README.md
- ChangeLog.md
- prelude.tin

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/htin#readme>

dependencies:
- ansi-terminal
- base >= 4.7 && < 5
- bytestring
- containers
- directory
- filepath
- formatting
- haskeline
- megaparsec
- mtl
- text
- time
- transformers

library:
  source-dirs: src
  default-extensions: 
  - OverloadedStrings

executables:
  htin:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall 
    - -Wincomplete-uni-patterns 
    - -Wincomplete-record-updates 
    - -Wmissing-import-lists
    - -fwarn-unused-imports
    - -fwarn-tabs
    dependencies:
    - htin

tests:
  htin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - htin
