module Colour.FourBit where

import           Data.Text (Text)

fgBlack :: Text
fgBlack         = "\x1b[30m"
bgBlack :: Text
bgBlack         = "\x1b[40m"
fgRed :: Text
fgRed           = "\x1b[31m"
bgRed :: Text
bgRed           = "\x1b[41m"
fgGreen :: Text
fgGreen         = "\x1b[32m"
bgGreen :: Text
bgGreen         = "\x1b[42m"
fgYellow :: Text
fgYellow        = "\x1b[33m"
bgYellow :: Text
bgYellow        = "\x1b[43m"
fgBlue :: Text
fgBlue          = "\x1b[34m"
bgBlue :: Text
bgBlue          = "\x1b[44m"
fgMagenta :: Text
fgMagenta       = "\x1b[35m"
bgMagenta :: Text
bgMagenta       = "\x1b[45m"
fgCyan :: Text
fgCyan          = "\x1b[36m"
bgCyan :: Text
bgCyan          = "\x1b[46m"
fgWhite :: Text
fgWhite         = "\x1b[37m"
bgWhite :: Text
bgWhite         = "\x1b[47m"
fgBrightBlack :: Text
fgBrightBlack   = "\x1b[90m"
bgBrightBlack :: Text
bgBrightBlack   = "\x1b[100m"
fgBrightRed :: Text
fgBrightRed     = "\x1b[91m"
bgBrightRed :: Text
bgBrightRed     = "\x1b[101m"
fgBrightGreen :: Text
fgBrightGreen   = "\x1b[92m"
bgBrightGreen :: Text
bgBrightGreen   = "\x1b[102m"
fgBrightYellow :: Text
fgBrightYellow  = "\x1b[93m"
bgBrightYellow :: Text
bgBrightYellow  = "\x1b[103m"
fgBrightBlue :: Text
fgBrightBlue    = "\x1b[94m"
bgBrightBlue :: Text
bgBrightBlue    = "\x1b[104m"
fgBrightMagenta :: Text
fgBrightMagenta = "\x1b[95m"
bgBrightMagenta :: Text
bgBrightMagenta = "\x1b[105m"
fgBrightCyan :: Text
fgBrightCyan    = "\x1b[96m"
bgBrightCyan :: Text
bgBrightCyan    = "\x1b[106m"
fgBrightWhite :: Text
fgBrightWhite   = "\x1b[97m"
bgBrightWhite :: Text
bgBrightWhite   = "\x1b[107m"

cReset :: String
cReset = "\x1b[0m"


